name: 001_L2T_x4
model_type: lr_cls
num_threads: 4
print_freq: 45  # unit: iter
scale: 4
manual_seed: 200
deterministic: true
# test_only: true

# data and augmentation
data:
  path: datasets/CUB200
  train_resize_size: 256
  train_crop_size: 224
  val_resize_size: 256
  val_crop_size: 224

# network specs
network_cls:
  name: ResNet18
  num_classes: 200

# path for pretrained model
path:
  network_cls: ResNet18_Weights.IMAGENET1K_V1
  strict_load: false

# training config
train:  
  batch_size: 128  # 1 GPU
  epoch: 200
  save_freq: 50  # unit: epoch
  eval_freq: 10

  # optimizer
  optim_cls:
    type: SGD
    lr: !!float 3e-2
    momentum: 0.9
    weight_decay: !!float 1e-4
    
  # scheduler
  scheduler:
    type: CosineAnnealingRestartLR
    periods: [200]
    restart_weights: [1]
    eta_min: !!float 1e-4

  # losses
  ce_opt:
    type: CELoss
    label_smoothing: 0.0
    loss_weight: !!float 1.0

# training config
test:  
  batch_size: 32

# DDP setting
dist_url: env:://
