name: 030_SR_swinir_x4
model_type: sr_seg
num_threads: 16
print_freq: 45  # unit: iter
manual_seed: 200
scale: 4
deterministic: true

# data and augmentation
data:
  name: voc
  path: datasets/VOC
  base_size: 520
  crop_size: 480

# network specs
network_sr:
  name: swinir
  upscale: 4
  in_chans: 3
  img_size: 48
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
network_seg:
  name: deeplabv3_mobilenet_v3_large
  weights_backbone: MobileNet_V3_Large_Weights.IMAGENET1K_V1
  num_classes: 21
  aux_loss: true

# path for pretrained model
path:
  network_sr: experiments/pretrained_models/001_classicalSR_DIV2K_s48w8_SwinIR-M_x4.pth
  network_sr_key: params
  network_seg: ~

# training config
train:  
  batch_size: 4 # 4 GPU
  epoch: 100
  save_freq: 50  # unit: epoch
  eval_freq: 10

  sr_is_trainable: true
  seg_is_trainable: false

  # optimizer
  optim_sr:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.999]
  
  # scheduler
  scheduler_sr:
    type: CosineAnnealingRestartLR
    periods: [100]
    restart_weights: [1]
    eta_min: !!float 1e-6

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1.0
    reduction: mean

# training config
test:  
  batch_size: 1

# DDP setting
dist_url: env:://
