name: 023_SwT_edsr_x8
model_type: sr_det
num_threads: 16
print_freq: 100  # unit: iter
manual_seed: 100
scale: 8
deterministic: true
# test_only: true

# data and augmentation
data:
  path: datasets/VOC_COCO
  format: coco
  aspect_ratio_group_factor : 3
  data_augmentation: hflip
  is_voc: true

# network specs
network_sr:
  name: edsr
  n_blocks: 16
  n_feats: 64
network_det:
  name: fasterrcnn_mobilenet_v3_large_fpn
  weights_backbone: MobileNet_V3_Large_Weights.IMAGENET1K_V1
  num_classes: 21

# path for pretrained model
path:
  network_sr: experiments/pretrained_models/edsr_baseline_x8.pt
  network_seg: ~

# training config
train:  
  batch_size: 16  # 1 GPU
  epoch: 30
  save_freq: 10  # unit: epoch
  eval_freq: 5

  sr_is_trainable: true
  det_is_trainable: true

  # optimizer
  optim_sr:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.999]
  optim_det:
    type: SGD
    lr: !!float 2e-2
    momentum: 0.9
    weight_decay: !!float 1e-4
  
  # scheduler
  scheduler_sr:
    type: CosineAnnealingRestartLR
    periods: [30]
    restart_weights: [1]
    eta_min: !!float 1e-6
  scheduler_det:
    type: CosineAnnealingRestartLR
    periods: [30]
    restart_weights: [1]
    eta_min: !!float 1e-4

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1.0
    reduction: mean
  det_opt:
    type: DETLoss
    loss_weight: !!float 1.0

# training config
test:  
  batch_size: 1

# DDP setting
dist_url: env:://
