name: 031_S2T_swinir_x4
model_type: sr_det
num_threads: 16
print_freq: 100  # unit: iter
manual_seed: 100
scale: 4
deterministic: true
# test_only: true

# data and augmentation
data:
  path: datasets/VOC_COCO
  format: coco
  aspect_ratio_group_factor : 3
  data_augmentation: hflip
  is_voc: true

# network specs
network_sr:
  name: swinir
  upscale: 4
  in_chans: 3
  img_size: 48
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
network_det:
  name: fasterrcnn_mobilenet_v3_large_fpn
  weights_backbone: MobileNet_V3_Large_Weights.IMAGENET1K_V1
  num_classes: 21

# path for pretrained model
path:
  network_sr: experiments/det/030_SR_swinir_x4/models/net_sr_030.pth
  network_det: ~

# training config
train:  
  batch_size: 4  # 4 GPU
  epoch: 30
  save_freq: 10  # unit: epoch
  eval_freq: 10

  sr_is_trainable: false
  det_is_trainable: true

  # optimizer
  optim_det:
    type: SGD
    lr: !!float 2e-2
    momentum: 0.9
    weight_decay: !!float 1e-4
  
  # scheduler
  scheduler_det:
    type: CosineAnnealingRestartLR
    periods: [30]
    restart_weights: [1]
    eta_min: !!float 1e-4

  # losses
  det_opt:
    type: DETLoss
    loss_weight: !!float 1.0

# training config
test:  
  batch_size: 1

# DDP setting
dist_url: env:://
